#!/usr/bin/env python3
#
# Support file for node: vision_processing
# 

import os
import cv2
import numpy as np

import subprocess
from ament_index_python.packages import get_package_prefix


###################
## Class Methods ##
###################

def clean_maurer_path(self, maurer_image: np.ndarray) -> str:
    """
    Post-process image generated by the Dream3D Maurer Filter Pipeline.

    :param maurer_image_filepath: OpenCV Image D3D Maurer filtered maze
    :return: Saves new Image (maze_maurer_path.tiff)
    """

    # Find number of all-black rows on header
    first_row = 0
    whites = np.argwhere(maurer_image[first_row,:] == 255)
    while len(whites) == 0:
        first_row += 1
        whites = np.argwhere(maurer_image[first_row,:] == 255)

    # Force Single White pixel along top of maze
    first = True
    for i in whites:
        if first: first_col = i
        if not first:  maurer_image[0,i] = 0
        first = False

    # Draw WhiteLine straight up from the start pixel
    while first_row > 0:
        first_row -= 1
        maurer_image[first_row, first_col] = 255

    # Find first bottom row containing white pixels
    last_row = maurer_image.shape[0] - 1
    whites = np.argwhere(maurer_image[last_row,:] == 255)
    while len(whites) == 0:
        last_row -= 1
        whites = np.argwhere(maurer_image[last_row,:] == 255)

    # Draw WhiteLine straight down from all white pixels along bottom-most white pixel containing row
    while last_row < maurer_image.shape[0]-1:
        last_row += 1
        for col in whites:
            maurer_image[last_row, col] = 255

    filepath_maurer_path = os.path.join(self.dir_wksp, 'maze_maurer_cleaned.tiff')
    cv2.imwrite(filepath_maurer_path, maurer_image)
    # cv2.imshow("Fixed Mauer Path Entrance", maurer_image)
    # cv2.waitKey(0)

    return maurer_image



def call_path_solver(self, filepath_maurer_path) -> tuple:
    """
    Wapper around Python Maze Solver script.

    :param path_image_cropped: Absolute file path to the cropped maze
    :return: Filename (less extension)  (maze_maurer_path.tiff)
    """
    #todo: using this as a wrapper. In future, covert solver to a python class and import

    # Directories and Filepaths
    solver          = os.path.join(self.dir_pkg, 'include/mazesolving/solve.py')
    output_filename = os.path.join(self.dir_wksp, 'path_solved')

    # Logs
    solver_output_path = os.path.join(self.dir_log, 'log_pathSolver.txt')
    solver_output = open(solver_output_path, 'w') # Workaround to supress output.

    # Run Solver
    subprocess.call(["python", solver, filepath_maurer_path, output_filename], stdout=solver_output, stderr=solver_output)

    return (str(output_filename) + '.csv', str(output_filename) + '.tiff')
    